export const FETCH_APPLICATION_LANGUAGE ="FETCH_APPLICATION_LANGUAGE"
export const SELECTED_LANGUAGE ="SELECTED_LANGUAGE"
export const TEST = "TEST";
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_PENDING = 'LOGIN_PENDING';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOG_OUT = 'LOG_OUT';
export const APP_UPDATE ="APP_UPDATE";
export const MANAGE_CONNECTIONS = "MANAGE_CONNECTIONS";
export const APP_SETTINGS = "APP_SETTINGS";
export const SECURITY_PRIVACY = "SECURITY_PRIVACY";
export const USER_INFO ="USER_INFO";
export const WALLET_INFO ="WALLET_INFO"
export const IS_CONNECTED_WALLET ="IS_CONNECTED_WALLET"
export const WALLET_ACCOUNT ="WALLET_ACCOUNT"
export const IS_GET_WALLET_DATA ="IS_GET_WALLET_DATA"


